name: amphi-notes
version: 1.0.0
license: Apache-2.0
summary: Notes Application
description: |
  A note-taking app created by Amphi

base: core22
confinement: classic
grade: stable

apps:
  notes:
    command: ./notes
    desktop: ./amphi-notes.desktop
    plugs:
      - network
      - x11
      - desktop
      - desktop-legacy
      - audio-playback

parts:
  notes:
    plugin: dump
    source:
      - on amd64: ./pre-built/x64
      - on arm64: ./pre-built/arm64
    stage:
      - data/*
      - lib/*
      - notes
      - amphi-notes.desktop
      - icon.png

architectures:
  - build-on: [ amd64 ]
  - build-on: [ arm64 ]