name: Windows build on ARM

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

env:
  FLUTTER_VERSION: "3.27.1"

jobs:
  build_for_windows_arm:
    runs-on: windows-2022
    strategy:
      matrix:
        architecture: [ arm64 ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version:  ${{ env.FLUTTER_VERSION }}
          channel: "stable"

      - name: Enable Windows Desktop
        run: flutter config --enable-windows-desktop

      - name: Install dependencies
        run: flutter pub get

      - name: Build Windows App
        run: flutter build windows

      - name: Upload on Artifact
        uses: actions/upload-artifact@v4
        with:
          name: notes-windows
          path: build/windows/runner/Release/*