name: test

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

env:
  FLUTTER_VERSION: "3.27.1"

jobs:
  build_tar:
    runs-on: windows-2022
    strategy:
      matrix:
        architecture: [ arm64 ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: sex
        run: |
          echo %PROCESSOR_ARCHITECTURE%

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version:  ${{ env.FLUTTER_VERSION }}
          channel: "stable"