name: AUR Release

on:
  workflow_dispatch:

env:
  FLUTTER_VERSION: "3.27.1"

jobs:
  aur_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download DEB
        run: |
          wget https://amphi.site/releases/notes/linux/x86/deb/notes-linux-x86-1.0.0.deb -O notes.deb
      - name: Get CheckSum
        run: |
          sha256sum notes.deb
          checksum=$(sha256sum notes.deb)