name: Build DEB on arm

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

env:
  FLUTTER_VERSION: "3.27.1"

jobs:
  build_deb:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang cmake libgtk-3-dev ninja-build libayatana-appindicator3-dev libfuse2 libmpv-dev mpv libmimalloc-dev libmimalloc2.0

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version:  ${{ env.FLUTTER_VERSION }}
          channel: "stable"

      - name: Enable Linux Desktop
        run: flutter config --enable-linux-desktop

      - name: Install dependencies
        run: flutter pub get

      - name: Build Linux App
        run: flutter build linux
