name: Build Snap

on:
  workflow_dispatch:

env:
  FLUTTER_VERSION: "3.27.1"

jobs:
  build_snap:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo systemctl enable --now docker

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version:  ${{ env.FLUTTER_VERSION }}
          channel: "stable"

      - name: Enable Linux Desktop
        run: flutter config --enable-linux-desktop

      - name: Install dependencies
        run: flutter pub get

      - name: Build Linux App
        run: flutter build linux

      - name: Build Snap Package Using Docker
        run: |
          docker run --rm \
            -v $PWD:/workspace \
            -w /workspace \
            snapcore/snapcraft:stable snapcraft

      - name: Upload Snap as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: flutter-snap-package
          path: notes.snap