name: Linux build

on:
  workflow_dispatch:

env:
  FLUTTER_VERSION: "3.24.5"
  APK_BUILD_DIR: "/tmp/build"

jobs:
  build:
    runs-on: ubuntu-20.04
    outputs:
      version: ${{ steps.get_version.outputs.version }}